name: Build Private APK

on:
  # Manual run button in Actions
  workflow_dispatch:

  # Auto-run when you publish a Release
  release:
    types: [published]

  # Also run on pushes to main and on version tags
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Android wrapper exists
        run: |
          if [ ! -d "android/app/src/main" ]; then
            echo "::error::android/ wrapper not found at repo root. Add the WebView Gradle project under android/."
            exit 1
          fi

            - name: Prepare assets (ensure index.html and app.settings.json)
        env:
          SHEETS_ENDPOINT: ${{ secrets.SHEETS_ENDPOINT }}
        run: |
          set -e
          # Always create the assets folder
          mkdir -p android/app/src/main/assets

          # Copy index.html from repo root
          if [ -f "index.html" ]; then
            cp index.html android/app/src/main/assets/index.html
            echo "Copied index.html into assets/"
          else
            echo "::error::index.html not found at repo root."
            exit 1
          fi

          # Handle app.settings.json
          if [ -f "app.settings.json" ]; then
            cp app.settings.json android/app/src/main/assets/app.settings.json
            echo "Copied app.settings.json into assets/"
          else
            if [ -n "$SHEETS_ENDPOINT" ]; then
              printf '%s\n' '{' \
                "  \"sheetsEndpoint\": \"${SHEETS_ENDPOINT}\"," \
                '  "cooldownDays": 90' \
              '}' > android/app/src/main/assets/app.settings.json
              echo "Created app.settings.json from SHEETS_ENDPOINT secret."
            else
              echo "::error::app.settings.json missing AND SHEETS_ENDPOINT secret not set."
              exit 1
            fi
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode keystore
        run: |
          set -e
          if [ -z "${{ secrets.KEYSTORE }}" ]; then
            echo "::error::KEYSTORE secret (Base64 keystore) is missing."
            exit 1
          fi
          echo "${{ secrets.KEYSTORE }}" | base64 -d > android/keystore.jks
          ls -l android/keystore.jks

      - name: Configure signing (gradle.properties)
        run: |
          {
            echo "MYAPP_UPLOAD_STORE_FILE=keystore.jks"
            echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}"
            echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}"
            echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_ALIAS_PASSWORD }}"
          } >> android/gradle.properties
          echo "gradle.properties configured."

      - name: Grant gradlew execute
        run: chmod +x android/gradlew || true

      - name: Build release
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Upload APK artifact (manual/push runs)
        uses: actions/upload-artifact@v4
        with:
          name: cascade_canvass_apk
          path: android/app/build/outputs/apk/release/*.apk

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cascade_canvass_apk
          path: dist

      - name: Attach APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
