name: Build Private APK

on:
  # Add this block so you can run it from the Actions tab
  workflow_dispatch:

  # (optional: still keep your auto triggers)
  push:
    branches: ["main", "release/*"]
    tags: ["v*"]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Copy your web UI + settings into the Android wrapper
      - name: Copy web assets into Android wrapper
        run: |
          mkdir -p android/app/src/main/assets
          cp index.html android/app/src/main/assets/index.html
          cp app.settings.json android/app/src/main/assets/app.settings.json

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Decode keystore from secret
      - name: Decode keystore
        run: |
          mkdir -p android
          echo "${{ secrets.KEYSTORE }}" | base64 -d > android/keystore.jks

      # Configure Gradle signing from secrets
      - name: Configure signing
        run: |
          cat >> android/gradle.properties <<EOF
          MYAPP_UPLOAD_STORE_FILE=keystore.jks
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_ALIAS_PASSWORD }}
          EOF

      - name: Grant gradlew execute
        run: chmod +x android/gradlew || true

      - name: Build release
        working-directory: android
        run: ./gradlew assembleRelease

      # Always publish the built APK as a workflow artifact (useful for branch builds)
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cascade_canvass_apk
          path: android/app/build/outputs/apk/release/*.apk

  # If a tag (v*) is pushed or a Release is published, attach the APK to the Release
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cascade_canvass_apk
          path: dist

      - name: Attach APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
